### PR TITLE
Fix URL property and syntax of RedOnion.version

### PR DESCRIPTION
**Pull request by DasSkelett**
The URL property of `RedOnion.version` points to a 404.
This PR fixes the path in the repository.

There was also a comma after `ALLOW_PRE_RELEASE`, which is not valid JSON (no commas after the last element of a object/dict).

Also interestingly the whole file was indented 5 and 9 spaces, I reduced it to the commonly seen 4 and 9.

Pinging @evandisoft since not everyone has pull request notifications enabled.

Shameless self-promotion:
I've written a GitHub Action that validates AVC version files and warns about problems like these when it finds them. It runs automatically after pushes to master and in pull requests, so errors can be caught before they make their way into a release.
https://github.com/DasSkelett/AVC-VersionFileValidator

### CODE REVIEW

**Comment by evandisoft** [comment]
Thank you. 

I think I might be responsible for that comma. It's allowed in javascript but not json.
Don't know why there was that indentation.

**Comment by evandisoft** [comment]
Thank you. I think I recall putting that comma there due to it being valid in javascript.

I don't actually know what the version file is used by. I always have to enter the version information manually when I submit the mod. But it's good to have some place to put the version number, of course.

**Comment by DasSkelett** [comment]
> I can't remember what, if anything, the version file is used by. I always have to enter the version information manually when I submit the mod. But it's good to have some place to put the version information, of course.

They come from [KSP-AVC](https://github.com/linuxgurugamer/KSP-AddonVersionChecker), which can check mods for updates in-game and warn if a mod is incompatible with the current KSP version.

However they are also heavily used by the CKAN to get KSP compatibility information of a mod, which, for mods hosted on GitHub, would have to be updated manually in the metadata for each new mod release otherwise.

**Comment by evandisoft** [comment]
I think in our case CKAN is just using the information I give it on Spacedock. But I will see, whenever there is a new release, if this new version changes any aspect of the process. If so, I'll consider using your github action.

**Comment by DasSkelett** [comment]
CKAN does use the version file to get compatibility data for this mod, due to defining the `$vref` in the .netkan file:
https://github.com/KSP-CKAN/NetKAN/blob/2001c1d71ebed06dd906b809da58ac81b883d260/NetKAN/RedOnion.netkan#L5
Which results in the following KSP range for the latest release:
https://github.com/KSP-CKAN/CKAN-meta/blob/b78ac5a1bac792696cf6bc86ed5de9832c3b2d5a/RedOnion/RedOnion-0.5.1.ckan#L11-L12
(1.8.0 - 1.9.9)
If CKAN wouldn't use the version file and only pull it from SpaceDock, the compatibility would only be `"kspo_version": "1.9.1"`.

This is the automated warning we got:
RedOnion-status

However it's true that the URL property doesn't change much as long as the remote file is the same as the one included in the download zip. But you _could_ use it to update the compatibility data in the future without having to release a new mod version, e.g. if KSP 1.10 comes out and you confirm that the current release still works fine, you can just edit this version file and CKAN would automatically detect it and change its own metadata.

**Pull request merged**
